# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy', models.DecimalField(decimal_places=4, max_digits=100000)),
                ('sale', models.DecimalField(decimal_places=4, max_digits=100000)),
                ('base_ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_exchange_rates', to='bank.Currency')),
                ('ccy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates', to='bank.Currency')),
            ],
        ),
    ]
